INSERT INTO `#__quiz` (`question`, `category`, `quiz_group`, `page`) VALUES 
('I build relational networks with individuals who are at the level I aspire to be.','Aspirant','Primary',1),
('I intentionally engage in professional development network groups.','Professional','Secondary',1),
('I build relationships with more experienced people or leaders to whom I go for advice','Mentor','Primary',1),
('I interact with other individuals who can hold me accountable','Accountability','Secondary',1),
('I am involved with professional networks that extend outside of my organization','Global','Secondary',1),
('I am involved in relationships that make me feel inadequate, uncomfortable or afraid','Toxic','Secondary',1),
('I take time for personal reflection or meditation','Personal','Primary',1),
('I work on developing strong relationships with those who work for me.','Subordinate','Primary',2),
('I am active or have membership in work-related professional associations.','Professional','Secondary',2),
('I reach out to established individuals in my life as sounding boards for my ideas','Mentor','Primary',2),
('I check for feedback regularly with a group of close peers','Accountability','Secondary',2),
('I engage in business and social media network groups','Global','Secondary',2),
('I interact with people that leave me drained or with a sick, nervous feeling in the pit of my stomach','Toxic','Secondary',2),
('I take advantage of personal development opportunities','Personal','Primary',2),
('I am intentional about networking with leaders or mentors who can influence my career advancement.','Aspirant','Primary',3),
('I connect with my colleagues in similar or related professional disciplines','Professional','Secondary',3),
('I ask experienced individuals for their input when I make difficult decisions','Mentor','Primary',3),
('I meet with others I trust or who can challenge me personally','Accountability','Secondary',3),
('I participate in community or non-work related groups','Global','Secondary',3),
('I am uncomfortable addressing negative relationships with confidence','Toxic','Secondary',3),
('I seek insight or spiritual wisdom for daily decision making','Personal','Primary',3),
('I foster relationships with individuals at lower levels in my organization.','Subordinate','Primary',4),
('I share my interest in career advancement with my peers','Professional','Secondary',4),
('I accept direction from leaders or others with more experience than I have','Mentor','Primary',4),
('I discuss my career goals with an inner circle that I have developed','Accountability','Secondary',4),
('I attend global and cross-cultural professional groups and events','Global','Secondary',4),
('I struggle to break away from individuals who constantly put me down or disrespect me','Toxic','Secondary',4),
('I connect to a resource that helps my spiritual development and self-awareness','Personal','Primary',4);